apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurator-dev
  labels:
    app: configurator-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configurator-dev
  template:
    metadata:
      labels:
        app: configurator-dev
    spec:
      containers:
      - name: configurator-dev
        resources:
           requests:
               cpu: 500m
               memory: 500Mi
           limits:
               cpu: 1000m
               memory: 1000Mi
        image: us.gcr.io/mymed-bridge-dev/configurator-service-dev:17
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: medbridge-dev-db-secret
                key: username

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: medbridge-dev-db-secret
                key: password

          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: medbridge-dev-db-secret
                key: host

          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: medbridge-dev-db-secret
                key: database
          
        ports:
        - containerPort: 9091
        volumeMounts:
        - name: configurator-dev
          mountPath: /etc/localtime
      volumes:
        - name: configurator-dev
          hostPath:
            path: /usr/share/zoneinfo/Asia/Colombo