apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-dev
  labels:
    app: core-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-dev
  template:
    metadata:
      labels:
        app: core-dev
    spec:
      containers:
      - name: core-dev
        resources:
           requests:
               cpu: 500m
               memory: 500Mi
           limits:
               cpu: 1000m
               memory: 1000Mi
        image: us.gcr.io/mymed-bridge-dev/core-service-dev:7
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: core-dev
          mountPath: /etc/localtime
      volumes:
        - name: core-dev
          hostPath:
            path: /usr/share/zoneinfo/Asia/Colombo