apiVersion: v1
data:
  tls.crt:
  tls.key:
kind: Secret
metadata:
  name: test-tls
  namespace: default
type: kubernetes.io/tls


#cat tls.crt | base64
#cat tls.key | base64


# To create TLS Secret object
# kubectl create secret tls medbridge-dev-secret --cert cert.crt --key digix.key