apiVersion: v1
kind: Service
metadata:
  name: configurator-dev-service
spec:
  type: NodePort
  selector:
      app: configurator-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9091