apiVersion: v1
kind: Service
metadata:
  name: core-dev-service
spec:
  type: NodePort
  selector:
    app: core-dev
  ports:
      - protocol: TCP
        port: 80
        targetPort: 8080