apiVersion: v1
kind: Secret
metadata:
  name: testsecret-tls
  namespace: default
data:
  tls.crt: base64 encoded cert
  tls.key: base64 encoded key
type: kubernetes.io/tls



# kubectl create secret tls first-secret-name \
#   --cert first-cert-file --key first-key-file


